steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA", "--build-arg=JAR_FILE=target/office-backend-0.0.1-SNAPSHOT.jar", "."]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]
timeout: '1600s'
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"

#steps:
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - '--no-cache'
#      - '-t'
#      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#      - office-backend
#      - '-f'
#      - office-backend/Dockerfile
#    id: Build
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - push
#      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#    id: Push
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'bash'
#    args: [ '-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]
#    id: Deploy
#images:
#  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#options:
#  substitutionOption: ALLOW_LOOSE
#substitutions:
#  _LABELS: gcb-trigger-id=0de9de13-6891-4891-ba24-65fda56ae705
#  _TRIGGER_ID: 0de9de13-6891-4891-ba24-65fda56ae705
#  _PLATFORM: managed
#  _SERVICE_NAME: flock-office-backend
#  _DEPLOY_REGION: europe-west4
#  _GCR_HOSTNAME: eu.gcr.io
#tags:
#  - gcp-cloud-build-deploy-cloud-run
#  - gcp-cloud-build-deploy-cloud-run-managed
#  - flock-office-backend