---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "office-frontend"
  namespace: "default"
  labels:
    app: "office-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "office-frontend"
  template:
    metadata:
      labels:
        app: "office-frontend"
    spec:
      containers:
        - name: "flock-office-frontend-sha256-1"
          image: "eu.gcr.io/flock-office-290609/office-monitoring/flock-office-frontend"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "office-frontend-hpa-9yx9"
  namespace: "default"
  labels:
    app: "office-frontend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "office-frontend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
